{% set version = "0.2.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-formattable
  version: {{ version|replace("-", "_") }}

source:
  fn: formattable_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/formattable_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/formattable/formattable_{{ version }}.tar.gz
  sha256: 4f0d4d2267d87a42da777066dd992c44fcc8ba9c0bdd2cbfc72980573b88bded

build:
  noarch: generic
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-knitr
    - r-rmarkdown
  run:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-knitr
    - r-rmarkdown

test:
  commands:
    - $R -e "library('formattable')"  # [not win]
    - "\"%R%\" -e \"library('formattable')\""  # [win]

about:
  home: https://renkun.me/formattable, https://github.com/renkun-ken/formattable
  license: MIT
  summary: Provides functions to create formattable vectors and data frames. 'Formattable' vectors are printed with text formatting, and formattable data frames are printed with multiple types of formatting in HTML to improve the readability of data presented in tabular form rendered in web pages.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
